---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgCVbjAXNc1kMpD9J7N4xs+K34He4U1+kPSJMJPsqNSi/grhl+CVcYe0WT9buUFrVkiKgu2Npzn2zY3ZjLiiKwrB8CB4C8YgizYNcrLHANBOlgX6ck5a/mGsppcjojCWr1jiCkIRd+W1elewSh6GoWUqnwEIt344U9efHBaexLxbG2BCXi5YTiEhVjtEWZhOgd6PuydKbB24Y7zYsUKXc0vJ4CilUvJvHbQoXEATikvjk+bXl5Xem+KwJpZQhARWmaFLlsg8OnqXCDRYPpCcprparTKnngB+6kggBC1HOFS38LZWoZqsXtG/HOSeMYp+VcvcwtXiyfIrl5v+vt7spynQZ/9/jgPY/KmAjIwO6K6oxvlRSeWiFX0zy/MT3seK8vjdE3MnuD1Cbb0f8ysTu4IddCaKwyJY3SvPQUdpm/FZUrNaPCjbxfMzF7YNFCynD5Bn0zB0FCvfmmzxj5rJcmgieBo/px8ENTyuYapO3V7YRTkWQOb/7SFEbra4bJ5eaxg7lUbu6B/hPFAVNlYYalAJ84uNmGEI/ZUqpoV7hLcg7xlXcP2sosbGvhwbNjwLz9Pk2pKc2jUTsLzVWwNJxToXPxrONjECzWCfsnAxot5CnyAX0lQaEcd/xPh3MG02P3UV7PI4NYlgGxgfEYS34YhfOyksWdljW8BnOOd1gIsnvVj+W4VbZdFHp2aLkzru7ZTBjKH0JyUkdDZpC8DriM//3cTAdg==
    admin-user: AgAxFSicuYdOGtrXZeEKnrrDLWj8L8UD0lTSGq1tWUYhIpIakDb4injQ1E28ObWckWJmU4aBjGKFwIMuFfwlajFSRGZQJmRiNtkiuXH48gl/tt8/79PTlTm+uXqyGFEIBQ9v4L1AgQGkZIsXUZnD7Hm0ThOxzwBuXGQ1RnwJrqLaCYKTd9BleeiATPy32rwFW78FkEpz63I2GGftl57wnOWx+/8brKiFdKskpHhEVF2eggVkEqKAmW6Cd5klN5EAOBEzjCxXQHxeCuJAGdadu/i7h+dYlbCNtGpaUYf3qqgljA0M81XRLIT1U+9DLowe4XAO83mRTaqxlioASz+1ykr4AZEiRnKfbALRQz1YBJXPjbQfdy45reHzAE46n/1uzJD5ldRQgbgLm/Xljpw3xZc1kmT19ooO4IfnoYzk0j+9CnMP+WbNybRorSb1K5hVIode1NvHSkiB2scAjwz7N8Yt/6UAmYs6HmEFXP31id8d7CJmFQ7aaP7y2uo6fvWUODtPC9U9PeCMyTVG+7RKyUGFQnfZnPpeFSfs++0YuC1KZS0mcwW9T1ufpaiZ9S772wjCHW6BxcfSKZ4QNBdxeNj/ghR0Bqq9TXLVArS0ILW3xsphkOZmAyP3AC6KywmE2nk8i/H4Aw4HQP49lpWCEqavpLu1OWduaqHUTPaKDhAC+4N8aAlpeo9b6wUlknVf25PEM3f0zg==
  template:
    metadata:
      name: grafana-admin
      namespace: monitoring
    type: Opaque
