---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgBD8oQXkCMXZVthD2DnXMdTZiPZk2jKMYv/vInVsljIJRatjOxJl/cPWVzZJwpgNAuxGZTEGfp7E/Bc4jWB5OAkHjGrZS1qOhfWqHsWgwxfPw5XWsD2qa+pvoth6SMUxQNgj1Zmvq6pHipWpFBhpgyr2rjPuDsra+yTTT67Tw0Q7z8No0lpbhdMKPuiYV0LOaX+rO4DzjaF/tDN2tIZupdewEwYSF0LDrnXUElo2hT5/JehA1qjD5xVrpNxGeQR6T8iB/LJgCv3DF0apk3fRmkZ/Bbew0zaabRXg2aRmvKjO8Vf+pPMU0i5ZO3JJjCPmO8L8fgmdZLmYrNeWy2tUV3LQsUvTrhFNCONKxss/w8dY0L+1GQa2kERN7eOd191MaY6Jz7pPm6+zFUvVSAcivbLqHycP+zUr9bZ4efjlvIwyETXvmPXvXQNx5t+YfnqbEpIXgtTN8P5R0jXCF6Bd1k+PZpaL4hOPCKJzvhOO/B6Da9QsrjRlQJe0vV6f4Jn5/EwjFWy7DCc7pC6NXzQMMvgx1HDcaaEVKSuJUffHdrD18zeBVmKGVenoKBU3P8EXW5g6LSafA8KCP9yodNtB2rH9aM6ESb2ozTWuNsKoSC6XyB9N5NrQhN6e0HzNPM2R3in8Ru0QFikwG5/cbaW2la+FD0oNBlfgAJx57x8PY3ibLCMdw72pbTu3z3bVHMXdaS1ku+6E/DXuSmPNVhBgPQ9unWSog==
    admin-user: AgBb0mOiRIYN548PCvHK9YZt5bEwzjdM5XuXMoY3uoYE7n7x7EHpI3Xgo8t8AhYZNnF7z6C1xs3liQq886v5Of/fm0ZgcGd7BN9u2pdu3XlIrXZLE6q+vQcpENbY4REPNrfhLekcHbalNrDdluIDfoJzAdEICw1Yi3YQRdbHHDHpMBdSBaPvSmnAXBEYJDXsLuzYgK42/t4BJoN8iw5npahQX/0WBgShjaBdMQOexQ1IHaTXuafB3QthEfBYvn3QEBIXtpoF9j7Vdyr8oJZrCe+E7fwiFWK5gvKtxgu9pgkJvFtPnkQ9ablk3N4gZyhvLxuUS3dFX88lTs0sn8e8oGi0kB9MPn+TuPNGBu2G6tPJcTY2xRRqkcMmNA05cttwAjWiWhh8pE8PdSG5VWCA41uOFwXjY+z5xPtTIaJziBRKOwVf0RNdqCxHFIBz72IwpXyuxEUZNlMfoZpbVmyBOOZzRkXgVGA9k/lB2dAApgApqD/iXrcpkiqrq2arFMJCQwKu/8wSFVqdxRR+MwJzba/Yu1lv0nIpM6a+l7Ngz5BY1uqfVM59rBOb9jBGXI9psO5HzlGjc1RdVODcOg31mlfAYTfFGzStYiS4jiu08+gft8CLdCeEI22Llh+iqHlT6f0uDCsjouOEb9xahaweTcUj5RvR4P9Swp2bSGjkMpn03d7buflsg1HzQJ8vPalYNCsRbGQH0H17pmE=
  template:
    metadata:
      name: grafana-admin
      namespace: monitoring
    type: Opaque
