---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgA+/QdFa/gOUW98ZRpk6Fn/YNtvuGughAq2OE9SIIgDm2Ree9d2Z92zHEC213jhweRTMXpMHklfgeAHHEVIG4rMP6xmaI84OlxDNVSigoS3fzEHtjFMITXqxFKH8lapx/bBNpbyEfeRf+cO3Ecn2enPBQR3knooWuSZAvLH41xvLDS6k/SwFa+IZCylGMbIXmNp82XkaVR+lbBwMrVDRtaYFTAlKYAO6UmU2v0Cw46sFVSgJzW9RaSjoZi7U30fz/WLJ1hFAx6++amZNLbpIlDwb9sQYMoFUtTwc3ZtSXEIoT8joXO15Nk7wzX5MjQeHAeYVLV6+c8HUUS0OTvttYkd/PGsV9gUdLZxY1fDD88/UxmzqWpbx2PMdXtodJI8hFtcOyUoo55LlM5jCrUOuqBA6jyRc8OXkwliYk6N22ie6Bmvx8yhPnsEiU6R+VcnbHqmbsnnQ8+Z3ip029o3Eg13mT1F+hr4HFkMw7dzoZE41+LnK23LB/Ru6UYdOc7mmYZmULI9rNa1OzDUCIhKYrtkbRS2wXy6FlAd1ggmOsYz1cTriztHNax27x76zm3KtbA6/AAvQQzmpFpnw7VFC2Wopzl+3cB0cY/Od/VOvDTwf98zr4Sh0CKozldcqt1DYrcslxCXeJyTWbehZCv/b70NC8M4U5NUENxE4/a/QsDL+nNvTtrI9JYsuPUlkHsUkl+dLF31xMCUp8jb628UXWW8G+gV5VU=
    admin-user: AgC2rU5T9UYwlXTSWCdeQyzrNDqZq/zFlmZzAiJklAjIb69rOfwUh8gJpVtj4d4HGI6lep7puG31BGBVHFTy9I6q21q066Wa6/GKk6+FllVNvrAEsSKB7mPeixbcvB7WntINFOQWuGvzrOignbepycwYBiGnrQORoh820GOTWXdBIMPO90PYvHdzcl0PGPuQiOAHJGQooeKImF6HFDfsD2yl3KGVghdlRiGVo4nCwPcGfPQ7RC1PP/DhjzW+iuXHgguIblLfCFpwuHl9Vir5HbqOwIxkwnMImqnfIz2wC2cdu/LFu9QGqpnvvyOGZ3FM1hjIZ4DwVDIaihnesawjULOaApNcrcVy2+G45yvr+Bk8cNotN5J0VY0F9sxo7+QBoPmn2oBKgis7P9Fsi51nZSV6CCNCoM8S6TFCpIeSkfOK8XZM5p/lTgXIFt4qbOMoR4mOfMEcWGZLnvtfLG4fq2qTfLpF1uFWn/QXLfzo+M8aVCBiZ/F0z4NTUp8aL3hl6MswaoTPx/6rd0PckMBzt49zTlsPuUNk1j+x5cXfceSkmfI0LDU5SEOXRK/Yw6uM8O4IOZutrzqxJobezkv+yRAGRezUcPVwrsogDuXSmBK5SLJWr7qpMJkXy76/w2nl6qGVBVzTFgMNS/H+nOI5/af9womH/K/hWKhBTjS94X7R14a6uG7xz77gKLJv/e0pRNeseUt2pug=
  template:
    metadata:
      name: grafana-admin
      namespace: monitoring
    type: Opaque
