---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgBMULPQdkpQ09XKGZx0izpe8w2BALkDZFEQpQCzlVvI2FFiqEhfx/Tbq2HhbOGzWcLXZARXHlKd/YpR1PPIBoTC/mHlIJs41SPJjImAglsn7eD1KzTm7RuEuywkSX7UMUOgBOzspauCmqT534cxjiDoz/0xcuGoF0HuZoxv/gvs8RqQwhr9rHVkjsNswiPi3BlYv4E0ef7X/4MTRubu4faIiCX9FiVk2MiUKDXOP20V5vxFMBOsfBKR5tmxadTu4s9tS+BWGxFtdrCkaCha/QoA8EvyvZMIvNeA2ncjGvSZ/jmvLKHlLU/zqbK70uq38JSp4mU0c8zEAfcJp2oayuVWk6rpQMVCVgBoVPqMwMc/yGPUaskVWAmViysRjDZbP5ocN0KrFWmDra7lC3wp/ZSp86WHBeDJ6WYRlDxvwQnhRuYxYiDYMfqFDxrhgMEYEAgBGHy8fXGnLaYYHZvQJ/0AlktDZE/hRaDffnLCLDWlABTfiT1ruhEfjn2KxO9GHKpPmJzlflVEVAK0WRJu+lWjmx4NylE+hC/G9F2PEV1FKNqrgfarlf3fEV3JzA5dEctVyYpOWH0hGg/4uL04qBC0FiCYKACrKaSxA4C6PjlEwlRZK6/1+hC6SETsvl7lY5a1BRCYgQ/0IMCPa+I6+IJyGFdNspf4bHXBwVIMCZzPmJ3Qbys8Tdc9wnGXBtDp2qVgCi1Zwxzqnw==
    admin-user: AgAvAtj3GvsWKZcVl4Iygh6NMBPlid+fzUnHFXoKtYj1RF7E5ymzQJyYep5CYSg2fbchepKK8l8Mc7naSa9lt3Ruzx4g24Y1h9/nKsZALEF2DrCnEkDuWk0UUYdK4VPTnjwWK+ppDMpiml+V3IJVQpfv/VveJpTIix+XYpvfEfRfXeIicriAs7WlR1ryWfulrIuG5IrSW/efYCMT9uAOksi2av+ZOSeVrCk1KXtds6SVhEtqGk6zThyqvMXwT3gbMXZvPtc9pn/cFivDne/46gI9UE4vtoOVnnECA0MRskKV9+nSfIePaDtyN1lOLaMmRuKWQpGAUtEhQzjGli3eF77DmX4KcWeJAe241ef0QIrygERPYbkusfVsDXgEk9B0r53cz2RljIrNcysppngPetdWTfFMbY7vLCZaZgKJMl+Kv6C0W7jPomM3X11IaIcJU1NzE7bGLRo/yk8NABpUI1ud16/DVi/DwDqTcXowuGzrvFc9ByQejvcMmOaZsySWTTZKiSnacG18ZwmUN4KSwC3JZmkisq3u6izP0TKXKRbXYunKFMLDdOuMj+ZrgE/QeJL3HK8IU3aZuFcZpREM0FIKYfaSp2og+5Fxf6ApK/iqSg7RkOLAW65B4PDlwLKkvY1a6YFAP8x99M1pkZcfa37CT84I2+7AcTzfCnxJ9hNQM895voQsrMGFc3V/eucfx8Nvp2gfdeB91xI=
  template:
    metadata:
      name: grafana-admin
      namespace: monitoring
    type: Opaque
