apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cloudflared-tunnel-user
  namespace: components
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cloudflared-tunnel-user-binding
  namespace: components
subjects:
  - kind: ServiceAccount
    name: cloudflared-cloudflare-tunnel-remote
    namespace: components
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cloudflared-tunnel-user
