apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cloudflared
  namespace: components
spec:
  chart:
    spec:
      chart: cloudflare-tunnel-remote
      version: 0.1.2
      sourceRef:
        kind: HelmRepository
        name: cloudflared
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: cloudflared
  valuesFrom:
    - kind: ConfigMap
      name: cloudflared-values
      valuesKey: values.yaml
    - kind: Secret
      name: cloudflared-secret
      valuesKey: values.yaml
