apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: admin@only-a-user.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - selector:
          dnsZones:
            - "only-a-user.com"
        dns01:
          cloudflare:
            email: admin@only-a-user.com
            apiTokenSecretRef:
              name: cloudflare-api-token-secret
              key: api-token
