apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 15m
  url: oci://quay.io/jetstack/charts/cert-manager
  type: oci
