apiVersion: source.toolkit.fluxcd.io/v2
kind: OCIRepository
metadata:
  name: forgejo
  namespace: flux-system
spec:
  interval: 1h0m0s
  url: oci://code.forgejo.org/forgejo-helm/forgejo
  ref:
    tag: 12.5.3
