apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: forgejo
  namespace: flux-system
spec:
  interval: 15m
  url: oci://code.forgejo.org/forgejo-helm/forgejo
  ref:
    tag: 15.0.1
