apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: reflector
  namespace: flux-system
spec:
  interval: 15m
  url: oci://ghcr.io/emberstack/helm-charts/reflector
  ref:
    tag: 9.1.36
