apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pangolin-newt
  namespace: tunnel-components
spec:
  interval: 15m
  timeout: 5m
  chart:
    spec:
      chart: newt
      version: 1.1.0
      sourceRef:
        kind: HelmRepository
        name: pangolin-newt
        namespace: flux-system
  install:
    disableSchemaValidation: true
  upgrade:
    disableSchemaValidation: true
  values:
    newtInstances:
      - name: "main"
        enabled: true
        auth:
          existingSecretName: "newt-pangolin-secret"
          keys:
            endpointKey: PANGOLIN_ENDPOINT
            idKey: NEWT_ID
            secretKey: NEWT_SECRET
