apiVersion: v1
kind: Service
metadata:
  name: external-glance-tcp-svc
  namespace: external-routes
spec:
  ports:
    - name: https
      port: 443
---
apiVersion: v1
kind: Endpoints
metadata:
  name: external-glance-tcp-svc
  namespace: external-routes
subsets:
  - addresses:
      - ip: 10.10.120.18
    ports:
      - name: https
        port: 443
---
apiVersion: v1
kind: Service
metadata:
  name: external-glance-http-svc
  namespace: external-routes
spec:
  ports:
    - name: http
      port: 80
---
apiVersion: v1
kind: Endpoints
metadata:
  name: external-glance-http-svc
  namespace: external-routes
subsets:
  - addresses:
      - ip: 10.10.120.18
    ports:
      - name: http
        port: 80
