apiVersion: v1
kind: Service
metadata:
  name: external-opencloud-tcp-svc
  namespace: external-routes
spec:
  ports:
    - name: https
      port: 443
---
apiVersion: v1
kind: Endpoints
metadata:
  name: external-opencloud-tcp-svc
  namespace: external-routes
subsets:
  - addresses:
      - ip: 10.10.111.107
    ports:
      - name: https
        port: 443
---
apiVersion: v1
kind: Service
metadata:
  name: external-opencloud-http-svc
  namespace: external-routes
spec:
  ports:
    - name: http
      port: 80
---
apiVersion: v1
kind: Endpoints
metadata:
  name: external-opencloud-http-svc
  namespace: external-routes
subsets:
  - addresses:
      - ip: 10.10.111.107
    ports:
      - name: http
        port: 80
