apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: harbor
  namespace: flux-system
spec:
  interval: 15m
  path: apps/harbor
  prune: true
  timeout: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: server
